name: Blue Green Deploy

on:
  push:
    paths:
      - "app/**"
      - "k8s/**"
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: dev-eks
  IMAGE_NAME: myapp

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION |
          docker login --username AWS \
          --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build and Push
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} ./app
          docker tag $IMAGE_NAME:${{ github.sha }} \
            ${{ secrets.ECR_REGISTRY }}/$IMAGE_NAME:${{ github.sha }}
          docker push \
            ${{ secrets.ECR_REGISTRY }}/$IMAGE_NAME:${{ github.sha }}

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name $CLUSTER_NAME \
            --region $AWS_REGION

      # Deploy GREEN
      - name: Deploy Green
        run: |
          kubectl apply -f k8s/base/service-green.yaml
          kubectl apply -f k8s/base/deployment-green.yaml
          kubectl set image deployment/app-green \
            app=${{ secrets.ECR_REGISTRY }}/$IMAGE_NAME:${{ github.sha }}

      - name: Wait for rollout
        run: kubectl rollout status deployment/app-green

      # Shift 50%
      - name: Shift 50% Traffic
        run: |
          kubectl annotate ingress app-ingress \
          alb.ingress.kubernetes.io/actions.weighted-routing='{
            "Type":"forward",
            "ForwardConfig":{
              "TargetGroups":[
                {"ServiceName":"app-blue","ServicePort":"80","Weight":50},
                {"ServiceName":"app-green","ServicePort":"80","Weight":50}
              ]
            }
          }' --overwrite

      - name: Wait 60 seconds
        run: sleep 60

      # Shift 100%
      - name: Shift 100% to Green
        run: |
          kubectl annotate ingress app-ingress \
          alb.ingress.kubernetes.io/actions.weighted-routing='{
            "Type":"forward",
            "ForwardConfig":{
              "TargetGroups":[
                {"ServiceName":"app-blue","ServicePort":"80","Weight":0},
                {"ServiceName":"app-green","ServicePort":"80","Weight":100}
              ]
            }
          }' --overwrite
